export const en = {
  // Header
  "header.title": "Arcana",
  "header.contact": "Contact me:",
  "header.slogan": "Grateful for your feedback — looking forward to working with you",

  // HomePage
  "home.headline1": "Unveil What the",
  "home.headline2": "Universe",
  "home.headline3": "Holds",
  "home.subtitle": "Draw from the ancient wisdom of Tarot. Ask a question, choose a spread, and let the cards speak.",

  // QuestionInput
  "question.placeholder": "What's on your mind? (optional)",

  // SpreadSelector
  "spread.label": "Choose Your Spread",
  "spread.single": "Single Card",
  "spread.single.desc": "Quick guidance for the moment",
  "spread.past-present": "Past · Present · Future",
  "spread.past-present.desc": "Understand how past, present, and future connect",
  "spread.problem-advice": "Problem · Obstacle · Advice",
  "spread.problem-advice.desc": "Identify the core issue and find a path forward",

  // DrawButton
  "draw.button": "Draw Cards",
  "draw.shuffling": "Shuffling...",

  // ResultPage
  "result.newReading": "New Reading",
  "result.reshuffle": "Reshuffle",
  "result.singleLabel": "Single Card Reading",
  "result.threeLabel": "Three Card Reading",

  // CardFace
  "card.majorArcana": "Major Arcana",
  "card.reversed": "Reversed",
  "card.upright": "Upright",

  // Spread positions
  "position.single": "Your Card",
  "position.past": "Past",
  "position.present": "Present",
  "position.future": "Future",
  "position.problem": "Problem",
  "position.obstacle": "Obstacle",
  "position.advice": "Advice",

  // Suits
  "suit.cups": "Cups",
  "suit.wands": "Wands",
  "suit.swords": "Swords",
  "suit.pentacles": "Pentacles",

  // SummaryBlock
  "summary.title": "Your Reading",

  // Interpretation engine
  "interpret.allReversed": "All cards appear reversed, suggesting significant internal resistance or external obstacles at play.",
  "interpret.mostlyReversed": "More cards are reversed than upright, indicating a period of challenge and introspection.",
  "interpret.allUpright": "All cards are upright, suggesting clarity, forward momentum, and alignment.",
  "interpret.cupsDominant": "A strong emotional current runs through this reading. Matters of the heart, relationships, and intuition are at the forefront.",
  "interpret.wandsDominant": "Strong action energy is present. This reading speaks to ambition, creativity, and forward drive.",
  "interpret.swordsDominant": "The intellect dominates. Logic, communication, and mental clarity — or conflict — are key themes.",
  "interpret.pentaclesDominant": "Material and practical concerns take center stage. Focus on finances, career, health, and tangible results.",
  "interpret.majorInfluence": "Multiple Major Arcana cards signal that fate or larger life forces are at work — this is not a trivial matter.",
  "interpret.singleFrame": "This card represents the core energy surrounding your situation right now.",
  "interpret.singleFrameQ": "This card represents the core energy surrounding your question right now.",
  "interpret.pastPresentFrame": "The Past card reveals the foundation, the Present card shows your current state, and the Future card hints at what is unfolding.",
  "interpret.problemAdviceFrame": "The Problem card identifies the core issue, the Obstacle card reveals what stands in your way, and the Advice card offers guidance forward.",

  // Themes
  "theme.strongResistance": "Strong Resistance",
  "theme.challenge": "Challenge",
  "theme.clarity": "Clarity",
  "theme.cupsEnergy": "Cups Energy",
  "theme.wandsEnergy": "Wands Energy",
  "theme.swordsEnergy": "Swords Energy",
  "theme.pentaclesEnergy": "Pentacles Energy",
  "theme.majorInfluence": "Major Arcana Influence",
  "theme.cardSynergy": "Card Synergy",

  // Footer
  "footer.tos": "Terms of Service",
  "footer.privacy": "Privacy Policy",
  "footer.blog": "Blog",
  "footer.copyright": "© 2026 Tarot Web. All rights reserved.",

  // ToS Page
  "tos.title": "Terms of Service",
  "tos.content": `**Last updated: July 24, 2026**

## 1. Acceptance of Terms

By accessing and using Tarot Web ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please discontinue use of the Service.

## 2. Description of Service

Tarot Web is an online tarot card reading application provided for entertainment purposes only. The readings, interpretations, and content generated by the Service do not constitute professional advice (medical, legal, financial, or psychological).

## 3. User Conduct

You agree to use the Service only for lawful purposes and in a manner that does not infringe upon the rights of others.

## 4. Intellectual Property

All content, design, and code of the Service are the property of Tarot Web unless otherwise stated. The tarot card interpretations and original content are protected by copyright.

## 5. Disclaimer of Warranties

The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, or reliability of any readings or content.

## 6. Limitation of Liability

Tarot Web shall not be liable for any damages arising from the use or inability to use the Service, including but not limited to decisions made based on readings.

## 7. Changes to Terms

We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.

## 8. Contact

For questions about these terms: ztry666@qq.com`,

  // Privacy Page
  "privacy.title": "Privacy Policy",
  "privacy.content": `**Last updated: July 24, 2026**

## 1. Information We Collect

Tarot Web does not require user registration and does not knowingly collect personally identifiable information. We may collect non-personal usage data through third-party services (see Section 3).

## 2. Cookies

The Service uses cookies for essential functionality (such as remembering your language preference) and for third-party advertising. By using the Service, you consent to the use of cookies.

## 3. Third-Party Services

### Google AdSense

We display advertisements via Google AdSense, which may use cookies and web beacons to serve personalized ads based on your browsing history. Google's use of advertising cookies enables it and its partners to serve ads based on your visit to this site and/or other sites on the Internet.

You may opt out of personalized advertising by visiting [Google Ads Settings](https://www.google.com/settings/ads) or by using the [Network Advertising Initiative opt-out page](https://optout.networkadvertising.org/).

### Analytics

We may use analytics services to collect anonymized usage data (page views, visit duration, browser type) to improve the Service.

## 4. Data Storage

Language preference is stored locally in your browser via localStorage. No personal data is stored on our servers.

## 5. Children's Privacy

The Service is not directed to children under the age of 13. We do not knowingly collect personal information from children.

## 6. Your Rights

Since we do not collect personal identifiable information, there is no personal data to access, modify, or delete. For questions about this policy or your data, contact us at ztry666@qq.com.

## 7. Changes to This Policy

We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated revision date.

## 8. Contact

For privacy-related inquiries: ztry666@qq.com`,

  // Blog
  "blog.title": "Blog",
  "blog.backToList": "← Back to Blog",
  "blog.noPosts": "No articles yet. Check back soon!",
  "blog.publishedOn": "Published on",
  "blog.postNotFound": "Post not found.",
  "blog.loading": "Loading...",
} as const;

export type TranslationKey = keyof typeof en;
